# Generated by Django 4.2.5 on 2023-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(upload_to='perfil_picture/%Y/%m/%d')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
