# Generated by Django 4.2.5 on 2023-10-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfiluserbg_name_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluserbg',
            name='utilizar',
            field=models.BooleanField(default=False),
        ),
    ]
