# Generated by Django 4.2.5 on 2023-10-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_perfiluserbg_utilizar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiluserbg',
            options={'verbose_name': 'Plano de fundo', 'verbose_name_plural': 'Planos de fundo'},
        ),
    ]
